//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_Thoi_Trang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOAN
    {
        public int ID { get; set; }
        public string MADOAN { get; set; }
        public string TENDOAN { get; set; }
        public string TIENDO { get; set; }
        public Nullable<System.DateTime> NGAYBD { get; set; }
        public Nullable<System.DateTime> NGAYKT { get; set; }
    }
}
