//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_Thoi_Trang.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CT25Team16Entities : DbContext
    {
        public CT25Team16Entities()
            : base("name=CT25Team16Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DOAN> DOANs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<THANHVIEN> THANHVIENs { get; set; }
    }
}
