//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_Thoi_Trang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHVIEN
    {
        public string MSSV { get; set; }
        public string TENTV { get; set; }
        public string SDT { get; set; }
        public string EMAIL { get; set; }
    }
}
